# Generated by Django 5.1.1 on 2024-10-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
    ]
